name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build and Test
      run: | 
        cd Dinnr; \
        xcodebuild \
          -project Dinnr.xcodeproject
          -scheme Dinnr \
          -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' \
          clean test;
